### ISSUE TITLE
Use of hard coded pull-up is harmful

### ISSUE THREAD

**Issue by BiancoZandbergen** [xcore/sc_sdcard#2]
Both module_sdcard4bit and module_sdcardSPI hard coded enables the internal pull-up resistors on some ports. This will work fine on XS1-G devices that have pull-up resistors, but it will cause an exception on XS1-L devices because they do not have internal pull-up resistors (instead they have pull-down resistors).

Assumptions about the target device cannot be made implicitly. I propose to either fully rely on external pull-up resistors regarding the software or to pass a parameter to an initialization routine that will either do nothing or enable the internal pull-up depending on the value of the parameter.

**Comment by leleb** [comment]
You are right, Do you know if there is a way to check device type at runtime?
Or may be I'll add a #define to enable/disable the set_port_pull_up calls at compile time.

**Comment by BiancoZandbergen** [comment]
Checking the device type at runtime is indeed also a possible solution.

You can do this by reading processor switch register 0x00

For XS1-L this is:

<pre><code>
Address   Contents
0x00      Device ID register
            bits 7..0: XCore version, 0x0
            bits 15..8: XCore revision, 0x3
            bits 31..16: Node/Core number, taken from SSWitch
</code></pre>


Example code to check whether it is an XS1-G or XS1-L device:

<pre lang="c"><code>
#include <xs1.h>
#include <platform.h>
#include <stdio.h>

#define DEVICE_XS1_G 0x00000200U
#define DEVICE_XS1_L 0x00000300U

int is_device(unsigned id)
{
  unsigned val;
  read_pswitch_reg(get_core_id(), 0x00, val);
  
  if ( (val & ~0xFFFF0000) == id) {
    return 1;
  } else {
    return 0;
  } 
}

int main(void)
{
  
  if ( is_device(DEVICE_XS1_L) ) {
    printf("This is an XS1-L Device.\n");
  }
  
  if ( is_device(DEVICE_XS1_G) ) {
    printf("This is an XS1-G Device.\n");
  }
  
  return 0;
}
</code></pre>


Still,  the user of the module should be made aware whether external pull-ups are required or not.
